# Generated by Django 5.2.14 on 2026-05-23 05:44

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, validators=[profiles.models.validate_timezone]),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, validators=[profiles.models.validate_timezone]),
        ),
    ]
